// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/auth/login.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*LoginRequest_UsernamePassword
	//	*LoginRequest_AuthToken
	Credentials   isLoginRequest_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_bricks_v1_auth_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_auth_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_auth_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetCredentials() isLoginRequest_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *LoginRequest) GetUsernamePassword() *UserPass {
	if x != nil {
		if x, ok := x.Credentials.(*LoginRequest_UsernamePassword); ok {
			return x.UsernamePassword
		}
	}
	return nil
}

func (x *LoginRequest) GetAuthToken() *AuthToken {
	if x != nil {
		if x, ok := x.Credentials.(*LoginRequest_AuthToken); ok {
			return x.AuthToken
		}
	}
	return nil
}

type isLoginRequest_Credentials interface {
	isLoginRequest_Credentials()
}

type LoginRequest_UsernamePassword struct {
	UsernamePassword *UserPass `protobuf:"bytes,1,opt,name=username_password,json=usernamePassword,proto3,oneof"`
}

type LoginRequest_AuthToken struct {
	AuthToken *AuthToken `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3,oneof"`
}

func (*LoginRequest_UsernamePassword) isLoginRequest_Credentials() {}

func (*LoginRequest_AuthToken) isLoginRequest_Credentials() {}

type UserPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPass) Reset() {
	*x = UserPass{}
	mi := &file_bricks_v1_auth_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPass) ProtoMessage() {}

func (x *UserPass) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_auth_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPass.ProtoReflect.Descriptor instead.
func (*UserPass) Descriptor() ([]byte, []int) {
	return file_bricks_v1_auth_login_proto_rawDescGZIP(), []int{1}
}

func (x *UserPass) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserPass) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenSource   string                 `protobuf:"bytes,1,opt,name=token_source,json=tokenSource,proto3" json:"token_source,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_bricks_v1_auth_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_auth_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_bricks_v1_auth_login_proto_rawDescGZIP(), []int{2}
}

func (x *AuthToken) GetTokenSource() string {
	if x != nil {
		return x.TokenSource
	}
	return ""
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_bricks_v1_auth_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_auth_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_auth_login_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

var File_bricks_v1_auth_login_proto protoreflect.FileDescriptor

const file_bricks_v1_auth_login_proto_rawDesc = "" +
	"\n" +
	"\x1abricks/v1/auth/login.proto\x12\x0ebricks.v1.auth\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\fLoginRequest\x12G\n" +
	"\x11username_password\x18\x01 \x01(\v2\x18.bricks.v1.auth.UserPassH\x00R\x10usernamePassword\x12:\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x19.bricks.v1.auth.AuthTokenH\x00R\tauthTokenB\r\n" +
	"\vcredentials\"B\n" +
	"\bUserPass\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"D\n" +
	"\tAuthToken\x12!\n" +
	"\ftoken_source\x18\x01 \x01(\tR\vtokenSource\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x8b\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry2n\n" +
	"\vAuthService\x12_\n" +
	"\x05Login\x12\x1c.bricks.v1.auth.LoginRequest\x1a\x1d.bricks.v1.auth.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/loginB\xb5\x01\n" +
	"\x12com.bricks.v1.authB\n" +
	"LoginProtoP\x01Z9github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/auth\xa2\x02\x03BVA\xaa\x02\x0eBricks.V1.Auth\xca\x02\x0eBricks\\V1\\Auth\xe2\x02\x1aBricks\\V1\\Auth\\GPBMetadata\xea\x02\x10Bricks::V1::Authb\x06proto3"

var (
	file_bricks_v1_auth_login_proto_rawDescOnce sync.Once
	file_bricks_v1_auth_login_proto_rawDescData []byte
)

func file_bricks_v1_auth_login_proto_rawDescGZIP() []byte {
	file_bricks_v1_auth_login_proto_rawDescOnce.Do(func() {
		file_bricks_v1_auth_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_auth_login_proto_rawDesc), len(file_bricks_v1_auth_login_proto_rawDesc)))
	})
	return file_bricks_v1_auth_login_proto_rawDescData
}

var file_bricks_v1_auth_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bricks_v1_auth_login_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: bricks.v1.auth.LoginRequest
	(*UserPass)(nil),              // 1: bricks.v1.auth.UserPass
	(*AuthToken)(nil),             // 2: bricks.v1.auth.AuthToken
	(*LoginResponse)(nil),         // 3: bricks.v1.auth.LoginResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_bricks_v1_auth_login_proto_depIdxs = []int32{
	1, // 0: bricks.v1.auth.LoginRequest.username_password:type_name -> bricks.v1.auth.UserPass
	2, // 1: bricks.v1.auth.LoginRequest.auth_token:type_name -> bricks.v1.auth.AuthToken
	4, // 2: bricks.v1.auth.LoginResponse.expiry:type_name -> google.protobuf.Timestamp
	0, // 3: bricks.v1.auth.AuthService.Login:input_type -> bricks.v1.auth.LoginRequest
	3, // 4: bricks.v1.auth.AuthService.Login:output_type -> bricks.v1.auth.LoginResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bricks_v1_auth_login_proto_init() }
func file_bricks_v1_auth_login_proto_init() {
	if File_bricks_v1_auth_login_proto != nil {
		return
	}
	file_bricks_v1_auth_login_proto_msgTypes[0].OneofWrappers = []any{
		(*LoginRequest_UsernamePassword)(nil),
		(*LoginRequest_AuthToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_auth_login_proto_rawDesc), len(file_bricks_v1_auth_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_auth_login_proto_goTypes,
		DependencyIndexes: file_bricks_v1_auth_login_proto_depIdxs,
		MessageInfos:      file_bricks_v1_auth_login_proto_msgTypes,
	}.Build()
	File_bricks_v1_auth_login_proto = out.File
	file_bricks_v1_auth_login_proto_goTypes = nil
	file_bricks_v1_auth_login_proto_depIdxs = nil
}
