// Code generated by MockGen. DO NOT EDIT.
// Source: matchmaking/request_match.pb.go
//
// Generated by this command:
//
//	mockgen -source matchmaking/request_match.pb.go -destination matchmaking/mock/request_match.pb.go -package mockmatchmaking
//

// Package mockmatchmaking is a generated GoMock package.
package mockmatchmaking

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockisRequestMatchResponse_Update is a mock of isRequestMatchResponse_Update interface.
type MockisRequestMatchResponse_Update struct {
	ctrl     *gomock.Controller
	recorder *MockisRequestMatchResponse_UpdateMockRecorder
	isgomock struct{}
}

// MockisRequestMatchResponse_UpdateMockRecorder is the mock recorder for MockisRequestMatchResponse_Update.
type MockisRequestMatchResponse_UpdateMockRecorder struct {
	mock *MockisRequestMatchResponse_Update
}

// NewMockisRequestMatchResponse_Update creates a new mock instance.
func NewMockisRequestMatchResponse_Update(ctrl *gomock.Controller) *MockisRequestMatchResponse_Update {
	mock := &MockisRequestMatchResponse_Update{ctrl: ctrl}
	mock.recorder = &MockisRequestMatchResponse_UpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockisRequestMatchResponse_Update) EXPECT() *MockisRequestMatchResponse_UpdateMockRecorder {
	return m.recorder
}

// isRequestMatchResponse_Update mocks base method.
func (m *MockisRequestMatchResponse_Update) isRequestMatchResponse_Update() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isRequestMatchResponse_Update")
}

// isRequestMatchResponse_Update indicates an expected call of isRequestMatchResponse_Update.
func (mr *MockisRequestMatchResponse_UpdateMockRecorder) isRequestMatchResponse_Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isRequestMatchResponse_Update", reflect.TypeOf((*MockisRequestMatchResponse_Update)(nil).isRequestMatchResponse_Update))
}
