// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/item/v1/persistence/item.proto

package persistence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item describes an item available in the catalog.
type Item struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Flags                uint64                 `protobuf:"fixed64,3,opt,name=flags,proto3" json:"flags,omitempty"`
	AvailabilitySchedule []*TimeRange           `protobuf:"bytes,4,rep,name=availability_schedule,json=availabilitySchedule,proto3" json:"availability_schedule,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_bricks_item_v1_persistence_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_item_v1_persistence_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_bricks_item_v1_persistence_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Item) GetAvailabilitySchedule() []*TimeRange {
	if x != nil {
		return x.AvailabilitySchedule
	}
	return nil
}

// TimeRange describes a period of time. If from is omitted, the range extends to the beginning of time; similarly for to
// and the end of time.
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_bricks_item_v1_persistence_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_item_v1_persistence_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_bricks_item_v1_persistence_item_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TimeRange) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

var File_bricks_item_v1_persistence_item_proto protoreflect.FileDescriptor

const file_bricks_item_v1_persistence_item_proto_rawDesc = "" +
	"\n" +
	"%bricks/item/v1/persistence/item.proto\x12\x1abricks.item.v1.persistence\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\x06R\x05flags\x12Z\n" +
	"\x15availability_schedule\x18\x04 \x03(\v2%.bricks.item.v1.persistence.TimeRangeR\x14availabilitySchedule\"\x81\x01\n" +
	"\tTimeRange\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\xff\x01\n" +
	"\x1ecom.bricks.item.v1.persistenceB\tItemProtoP\x01ZFgithub.com/purplepudding/bricks/item/pkg/pb/bricks/item/v1/persistence\xa2\x02\x04BIVP\xaa\x02\x1aBricks.Item.V1.Persistence\xca\x02\x1aBricks\\Item\\V1\\Persistence\xe2\x02&Bricks\\Item\\V1\\Persistence\\GPBMetadata\xea\x02\x1dBricks::Item::V1::Persistenceb\x06proto3"

var (
	file_bricks_item_v1_persistence_item_proto_rawDescOnce sync.Once
	file_bricks_item_v1_persistence_item_proto_rawDescData []byte
)

func file_bricks_item_v1_persistence_item_proto_rawDescGZIP() []byte {
	file_bricks_item_v1_persistence_item_proto_rawDescOnce.Do(func() {
		file_bricks_item_v1_persistence_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_item_v1_persistence_item_proto_rawDesc), len(file_bricks_item_v1_persistence_item_proto_rawDesc)))
	})
	return file_bricks_item_v1_persistence_item_proto_rawDescData
}

var file_bricks_item_v1_persistence_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bricks_item_v1_persistence_item_proto_goTypes = []any{
	(*Item)(nil),                  // 0: bricks.item.v1.persistence.Item
	(*TimeRange)(nil),             // 1: bricks.item.v1.persistence.TimeRange
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_bricks_item_v1_persistence_item_proto_depIdxs = []int32{
	1, // 0: bricks.item.v1.persistence.Item.availability_schedule:type_name -> bricks.item.v1.persistence.TimeRange
	2, // 1: bricks.item.v1.persistence.TimeRange.from:type_name -> google.protobuf.Timestamp
	2, // 2: bricks.item.v1.persistence.TimeRange.to:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bricks_item_v1_persistence_item_proto_init() }
func file_bricks_item_v1_persistence_item_proto_init() {
	if File_bricks_item_v1_persistence_item_proto != nil {
		return
	}
	file_bricks_item_v1_persistence_item_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_item_v1_persistence_item_proto_rawDesc), len(file_bricks_item_v1_persistence_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bricks_item_v1_persistence_item_proto_goTypes,
		DependencyIndexes: file_bricks_item_v1_persistence_item_proto_depIdxs,
		MessageInfos:      file_bricks_item_v1_persistence_item_proto_msgTypes,
	}.Build()
	File_bricks_item_v1_persistence_item_proto = out.File
	file_bricks_item_v1_persistence_item_proto_goTypes = nil
	file_bricks_item_v1_persistence_item_proto_depIdxs = nil
}
