resources:
  - ../base
  - resources/ingress.yaml
configMapGenerator:
  - name: gateway-config
    namespace: bricks
    envs:
      - config.env
images:
  - name: ghcr.io/purplepudding/bricks/gateway
    newTag: v0.24.3
