apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: {{.ProjectKebab}}

build:
  artifacts:
    - image: ghcr.io/purplepudding/bricks/{{.ProjectKebab}}
      ko:
        main: ./cmd/{{.ProjectKebab}}
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - internal
            - service
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: {{.ProjectKebab}}
    port: 80
    localPort: 8080