apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monolith

build:
  artifacts:
    - image: ghcr.io/purplepudding/foundation/monolith
      ko:
        main: ./cmd/monolith
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - service
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: monolith
    port: 80
    localPort: 8080