apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: monolith

build:
  artifacts:
    - image: ghcr.io/purplepudding/bricks/monolith
      ko:
        main: ./cmd/monolith
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - service
            - ../lib
            - ../go.mod
            - ../go.sum
            - ../auth
            - ../persistence
            - ../settings

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: auth
    namespace: bricks
    port: 80
    localPort: 8081
  - resourceType: service
    resourceName: persistence
    namespace: bricks
    port: 80
    localPort: 8082
  - resourceType: service
    resourceName: settings
    namespace: bricks
    port: 80
    localPort: 8083