apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: auth

build:
  artifacts:
    - image: ghcr.io/purplepudding/foundation/auth
      ko:
        main: ./cmd/auth
        dependencies:
          paths:
            - cmd
            - deploy
            - internal
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/base

portForward:
  - resourceType: service
    resourceName: auth
    port: 80
    localPort: 8080