apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bricks-gateway
  namespace: bricks
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: bricks.purplepudding.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
  tls:
    - hosts:
        - bricks.purplepudding.ddns.net
      secretName: bricks-gateway-cert-tls
