resources:
  - ../base
configMapGenerator:
  - name: matchmaking-config
    namespace: bricks
    envs:
      - config.env
images:
  - name: ghcr.io/purplepudding/bricks/matchmaking
    newTag: v0.24.4
