apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: settings

build:
  artifacts:
    - image: ghcr.io/purplepudding/foundation/settings
      ko:
        main: ./cmd/settings
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - internal
            - service
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: settings
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: settings-valkey
    port: 6379
    localPort: 6379