// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/matchmaking/request_match.proto

package matchmaking

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMatchRequest) Reset() {
	*x = RequestMatchRequest{}
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMatchRequest) ProtoMessage() {}

func (x *RequestMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMatchRequest.ProtoReflect.Descriptor instead.
func (*RequestMatchRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMatchRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RequestMatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RequestMatchResponse_AwaitingMatch
	//	*RequestMatchResponse_MatchFound
	Update        isRequestMatchResponse_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMatchResponse) Reset() {
	*x = RequestMatchResponse{}
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMatchResponse) ProtoMessage() {}

func (x *RequestMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMatchResponse.ProtoReflect.Descriptor instead.
func (*RequestMatchResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMatchResponse) GetUpdate() isRequestMatchResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RequestMatchResponse) GetAwaitingMatch() *AwaitingMatch {
	if x != nil {
		if x, ok := x.Update.(*RequestMatchResponse_AwaitingMatch); ok {
			return x.AwaitingMatch
		}
	}
	return nil
}

func (x *RequestMatchResponse) GetMatchFound() *MatchFound {
	if x != nil {
		if x, ok := x.Update.(*RequestMatchResponse_MatchFound); ok {
			return x.MatchFound
		}
	}
	return nil
}

type isRequestMatchResponse_Update interface {
	isRequestMatchResponse_Update()
}

type RequestMatchResponse_AwaitingMatch struct {
	AwaitingMatch *AwaitingMatch `protobuf:"bytes,1,opt,name=awaiting_match,json=awaitingMatch,proto3,oneof"`
}

type RequestMatchResponse_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,2,opt,name=match_found,json=matchFound,proto3,oneof"`
}

func (*RequestMatchResponse_AwaitingMatch) isRequestMatchResponse_Update() {}

func (*RequestMatchResponse_MatchFound) isRequestMatchResponse_Update() {}

type AwaitingMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitingMatch) Reset() {
	*x = AwaitingMatch{}
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitingMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitingMatch) ProtoMessage() {}

func (x *AwaitingMatch) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitingMatch.ProtoReflect.Descriptor instead.
func (*AwaitingMatch) Descriptor() ([]byte, []int) {
	return file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP(), []int{2}
}

type MatchFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP(), []int{3}
}

func (x *MatchFound) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchFound) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_matchmaking_request_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_bricks_v1_matchmaking_request_match_proto protoreflect.FileDescriptor

const file_bricks_v1_matchmaking_request_match_proto_rawDesc = "" +
	"\n" +
	")bricks/v1/matchmaking/request_match.proto\x12\x15bricks.v1.matchmaking\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x13RequestMatchRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\"\xb5\x01\n" +
	"\x14RequestMatchResponse\x12M\n" +
	"\x0eawaiting_match\x18\x01 \x01(\v2$.bricks.v1.matchmaking.AwaitingMatchH\x00R\rawaitingMatch\x12D\n" +
	"\vmatch_found\x18\x02 \x01(\v2!.bricks.v1.matchmaking.MatchFoundH\x00R\n" +
	"matchFoundB\b\n" +
	"\x06update\"\x0f\n" +
	"\rAwaitingMatch\"`\n" +
	"\n" +
	"MatchFound\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x127\n" +
	"\aplayers\x18\x02 \x03(\v2\x1d.bricks.v1.matchmaking.PlayerR\aplayers\",\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr2\xaa\x01\n" +
	"\x12MatchmakingService\x12\x93\x01\n" +
	"\fRequestMatch\x12*.bricks.v1.matchmaking.RequestMatchRequest\x1a+.bricks.v1.matchmaking.RequestMatchResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/matchmaking/request-match0\x01B\xe6\x01\n" +
	"\x19com.bricks.v1.matchmakingB\x11RequestMatchProtoP\x01Z@github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/matchmaking\xa2\x02\x03BVM\xaa\x02\x15Bricks.V1.Matchmaking\xca\x02\x15Bricks\\V1\\Matchmaking\xe2\x02!Bricks\\V1\\Matchmaking\\GPBMetadata\xea\x02\x17Bricks::V1::Matchmakingb\x06proto3"

var (
	file_bricks_v1_matchmaking_request_match_proto_rawDescOnce sync.Once
	file_bricks_v1_matchmaking_request_match_proto_rawDescData []byte
)

func file_bricks_v1_matchmaking_request_match_proto_rawDescGZIP() []byte {
	file_bricks_v1_matchmaking_request_match_proto_rawDescOnce.Do(func() {
		file_bricks_v1_matchmaking_request_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_matchmaking_request_match_proto_rawDesc), len(file_bricks_v1_matchmaking_request_match_proto_rawDesc)))
	})
	return file_bricks_v1_matchmaking_request_match_proto_rawDescData
}

var file_bricks_v1_matchmaking_request_match_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bricks_v1_matchmaking_request_match_proto_goTypes = []any{
	(*RequestMatchRequest)(nil),  // 0: bricks.v1.matchmaking.RequestMatchRequest
	(*RequestMatchResponse)(nil), // 1: bricks.v1.matchmaking.RequestMatchResponse
	(*AwaitingMatch)(nil),        // 2: bricks.v1.matchmaking.AwaitingMatch
	(*MatchFound)(nil),           // 3: bricks.v1.matchmaking.MatchFound
	(*Player)(nil),               // 4: bricks.v1.matchmaking.Player
}
var file_bricks_v1_matchmaking_request_match_proto_depIdxs = []int32{
	2, // 0: bricks.v1.matchmaking.RequestMatchResponse.awaiting_match:type_name -> bricks.v1.matchmaking.AwaitingMatch
	3, // 1: bricks.v1.matchmaking.RequestMatchResponse.match_found:type_name -> bricks.v1.matchmaking.MatchFound
	4, // 2: bricks.v1.matchmaking.MatchFound.players:type_name -> bricks.v1.matchmaking.Player
	0, // 3: bricks.v1.matchmaking.MatchmakingService.RequestMatch:input_type -> bricks.v1.matchmaking.RequestMatchRequest
	1, // 4: bricks.v1.matchmaking.MatchmakingService.RequestMatch:output_type -> bricks.v1.matchmaking.RequestMatchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bricks_v1_matchmaking_request_match_proto_init() }
func file_bricks_v1_matchmaking_request_match_proto_init() {
	if File_bricks_v1_matchmaking_request_match_proto != nil {
		return
	}
	file_bricks_v1_matchmaking_request_match_proto_msgTypes[1].OneofWrappers = []any{
		(*RequestMatchResponse_AwaitingMatch)(nil),
		(*RequestMatchResponse_MatchFound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_matchmaking_request_match_proto_rawDesc), len(file_bricks_v1_matchmaking_request_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_matchmaking_request_match_proto_goTypes,
		DependencyIndexes: file_bricks_v1_matchmaking_request_match_proto_depIdxs,
		MessageInfos:      file_bricks_v1_matchmaking_request_match_proto_msgTypes,
	}.Build()
	File_bricks_v1_matchmaking_request_match_proto = out.File
	file_bricks_v1_matchmaking_request_match_proto_goTypes = nil
	file_bricks_v1_matchmaking_request_match_proto_depIdxs = nil
}
