// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/item/catalog.proto

package item

import (
	common "github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels               []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Flags                uint64                 `protobuf:"fixed64,4,opt,name=flags,proto3" json:"flags,omitempty"`
	AvailabilitySchedule []*common.TimeRange    `protobuf:"bytes,5,rep,name=availability_schedule,json=availabilitySchedule,proto3" json:"availability_schedule,omitempty"`
	Version              uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Item) GetAvailabilitySchedule() []*common.TimeRange {
	if x != nil {
		return x.AvailabilitySchedule
	}
	return nil
}

func (x *Item) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Item          *Item                      `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	AssetBundle   map[string]*structpb.Value `protobuf:"bytes,2,rep,name=asset_bundle,json=assetBundle,proto3" json:"asset_bundle,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Parameters    map[string]*structpb.Value `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetResponse) GetAssetBundle() map[string]*structpb.Value {
	if x != nil {
		return x.AssetBundle
	}
	return nil
}

func (x *GetResponse) GetParameters() map[string]*structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.Pagination     `protobuf:"bytes,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetPage() *common.Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAvailableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_timestamp should only be permitted to be sent by certain classes of user (for example, a QA team or
	// playtesters). It is intended to allow testing of unreleased items, as it will be used to override the current
	// timestamp that would otherwise be used.
	RequestTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=request_timestamp,json=requestTimestamp,proto3,oneof" json:"request_timestamp,omitempty"`
	Page             *common.Pagination     `protobuf:"bytes,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAvailableRequest) Reset() {
	*x = ListAvailableRequest{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableRequest) ProtoMessage() {}

func (x *ListAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListAvailableRequest) GetRequestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTimestamp
	}
	return nil
}

func (x *ListAvailableRequest) GetPage() *common.Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableResponse) Reset() {
	*x = ListAvailableResponse{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableResponse) ProtoMessage() {}

func (x *ListAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListAvailableResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_item_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_item_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateItemResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_bricks_v1_item_catalog_proto protoreflect.FileDescriptor

const file_bricks_v1_item_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1cbricks/v1/item/catalog.proto\x12\x0ebricks.v1.item\x1a!bricks/v1/common/pagination.proto\x1a bricks/v1/common/timerange.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\x06R\x05flags\x12P\n" +
	"\x15availability_schedule\x18\x05 \x03(\v2\x1b.bricks.v1.common.TimeRangeR\x14availabilitySchedule\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x03\n" +
	"\vGetResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.bricks.v1.item.ItemR\x04item\x12O\n" +
	"\fasset_bundle\x18\x02 \x03(\v2,.bricks.v1.item.GetResponse.AssetBundleEntryR\vassetBundle\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.bricks.v1.item.GetResponse.ParametersEntryR\n" +
	"parameters\x1aV\n" +
	"\x10AssetBundleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"M\n" +
	"\vListRequest\x125\n" +
	"\x04page\x18\x01 \x01(\v2\x1c.bricks.v1.common.PaginationH\x00R\x04page\x88\x01\x01B\a\n" +
	"\x05_page\":\n" +
	"\fListResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.bricks.v1.item.ItemR\x05items\"\xba\x01\n" +
	"\x14ListAvailableRequest\x12L\n" +
	"\x11request_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x10requestTimestamp\x88\x01\x01\x125\n" +
	"\x04page\x18\x02 \x01(\v2\x1c.bricks.v1.common.PaginationH\x01R\x04page\x88\x01\x01B\x14\n" +
	"\x12_request_timestampB\a\n" +
	"\x05_page\"C\n" +
	"\x15ListAvailableResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.bricks.v1.item.ItemR\x05items\"=\n" +
	"\x11UpdateItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.bricks.v1.item.ItemR\x04item\".\n" +
	"\x12UpdateItemResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion2\xc2\x03\n" +
	"\x0eCatalogService\x12\\\n" +
	"\x03Get\x12\x1a.bricks.v1.item.GetRequest\x1a\x1b.bricks.v1.item.GetResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/items/by-id/{id}\x12X\n" +
	"\x04List\x12\x1b.bricks.v1.item.ListRequest\x1a\x1c.bricks.v1.item.ListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/items/all\x12y\n" +
	"\rListAvailable\x12$.bricks.v1.item.ListAvailableRequest\x1a%.bricks.v1.item.ListAvailableResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/items/available\x12}\n" +
	"\n" +
	"UpdateItem\x12!.bricks.v1.item.UpdateItemRequest\x1a\".bricks.v1.item.UpdateItemResponse\"(\x82\xd3\xe4\x93\x02\":\x04item\x1a\x1a/v1/items/update/{item.id}B\xb7\x01\n" +
	"\x12com.bricks.v1.itemB\fCatalogProtoP\x01Z9github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/item\xa2\x02\x03BVI\xaa\x02\x0eBricks.V1.Item\xca\x02\x0eBricks\\V1\\Item\xe2\x02\x1aBricks\\V1\\Item\\GPBMetadata\xea\x02\x10Bricks::V1::Itemb\x06proto3"

var (
	file_bricks_v1_item_catalog_proto_rawDescOnce sync.Once
	file_bricks_v1_item_catalog_proto_rawDescData []byte
)

func file_bricks_v1_item_catalog_proto_rawDescGZIP() []byte {
	file_bricks_v1_item_catalog_proto_rawDescOnce.Do(func() {
		file_bricks_v1_item_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_item_catalog_proto_rawDesc), len(file_bricks_v1_item_catalog_proto_rawDesc)))
	})
	return file_bricks_v1_item_catalog_proto_rawDescData
}

var file_bricks_v1_item_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bricks_v1_item_catalog_proto_goTypes = []any{
	(*Item)(nil),                  // 0: bricks.v1.item.Item
	(*GetRequest)(nil),            // 1: bricks.v1.item.GetRequest
	(*GetResponse)(nil),           // 2: bricks.v1.item.GetResponse
	(*ListRequest)(nil),           // 3: bricks.v1.item.ListRequest
	(*ListResponse)(nil),          // 4: bricks.v1.item.ListResponse
	(*ListAvailableRequest)(nil),  // 5: bricks.v1.item.ListAvailableRequest
	(*ListAvailableResponse)(nil), // 6: bricks.v1.item.ListAvailableResponse
	(*UpdateItemRequest)(nil),     // 7: bricks.v1.item.UpdateItemRequest
	(*UpdateItemResponse)(nil),    // 8: bricks.v1.item.UpdateItemResponse
	nil,                           // 9: bricks.v1.item.GetResponse.AssetBundleEntry
	nil,                           // 10: bricks.v1.item.GetResponse.ParametersEntry
	(*common.TimeRange)(nil),      // 11: bricks.v1.common.TimeRange
	(*common.Pagination)(nil),     // 12: bricks.v1.common.Pagination
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*structpb.Value)(nil),        // 14: google.protobuf.Value
}
var file_bricks_v1_item_catalog_proto_depIdxs = []int32{
	11, // 0: bricks.v1.item.Item.availability_schedule:type_name -> bricks.v1.common.TimeRange
	0,  // 1: bricks.v1.item.GetResponse.item:type_name -> bricks.v1.item.Item
	9,  // 2: bricks.v1.item.GetResponse.asset_bundle:type_name -> bricks.v1.item.GetResponse.AssetBundleEntry
	10, // 3: bricks.v1.item.GetResponse.parameters:type_name -> bricks.v1.item.GetResponse.ParametersEntry
	12, // 4: bricks.v1.item.ListRequest.page:type_name -> bricks.v1.common.Pagination
	0,  // 5: bricks.v1.item.ListResponse.items:type_name -> bricks.v1.item.Item
	13, // 6: bricks.v1.item.ListAvailableRequest.request_timestamp:type_name -> google.protobuf.Timestamp
	12, // 7: bricks.v1.item.ListAvailableRequest.page:type_name -> bricks.v1.common.Pagination
	0,  // 8: bricks.v1.item.ListAvailableResponse.items:type_name -> bricks.v1.item.Item
	0,  // 9: bricks.v1.item.UpdateItemRequest.item:type_name -> bricks.v1.item.Item
	14, // 10: bricks.v1.item.GetResponse.AssetBundleEntry.value:type_name -> google.protobuf.Value
	14, // 11: bricks.v1.item.GetResponse.ParametersEntry.value:type_name -> google.protobuf.Value
	1,  // 12: bricks.v1.item.CatalogService.Get:input_type -> bricks.v1.item.GetRequest
	3,  // 13: bricks.v1.item.CatalogService.List:input_type -> bricks.v1.item.ListRequest
	5,  // 14: bricks.v1.item.CatalogService.ListAvailable:input_type -> bricks.v1.item.ListAvailableRequest
	7,  // 15: bricks.v1.item.CatalogService.UpdateItem:input_type -> bricks.v1.item.UpdateItemRequest
	2,  // 16: bricks.v1.item.CatalogService.Get:output_type -> bricks.v1.item.GetResponse
	4,  // 17: bricks.v1.item.CatalogService.List:output_type -> bricks.v1.item.ListResponse
	6,  // 18: bricks.v1.item.CatalogService.ListAvailable:output_type -> bricks.v1.item.ListAvailableResponse
	8,  // 19: bricks.v1.item.CatalogService.UpdateItem:output_type -> bricks.v1.item.UpdateItemResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_bricks_v1_item_catalog_proto_init() }
func file_bricks_v1_item_catalog_proto_init() {
	if File_bricks_v1_item_catalog_proto != nil {
		return
	}
	file_bricks_v1_item_catalog_proto_msgTypes[3].OneofWrappers = []any{}
	file_bricks_v1_item_catalog_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_item_catalog_proto_rawDesc), len(file_bricks_v1_item_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_item_catalog_proto_goTypes,
		DependencyIndexes: file_bricks_v1_item_catalog_proto_depIdxs,
		MessageInfos:      file_bricks_v1_item_catalog_proto_msgTypes,
	}.Build()
	File_bricks_v1_item_catalog_proto = out.File
	file_bricks_v1_item_catalog_proto_goTypes = nil
	file_bricks_v1_item_catalog_proto_depIdxs = nil
}
