// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/common/pagination.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination defines how to select a portion of a large data set for a given request.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// last_id indicates the id of the last seen record, to indicate where the viewer currently is on the list. If unset,
	// should default to returning the first record according to the sort
	LastId *string `protobuf:"bytes,1,opt,name=last_id,json=lastId,proto3,oneof" json:"last_id,omitempty"`
	// count indicates how many records to return
	Count         uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_bricks_v1_common_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_common_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_bricks_v1_common_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLastId() string {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return ""
}

func (x *Pagination) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_bricks_v1_common_pagination_proto protoreflect.FileDescriptor

const file_bricks_v1_common_pagination_proto_rawDesc = "" +
	"\n" +
	"!bricks/v1/common/pagination.proto\x12\x10bricks.v1.common\"L\n" +
	"\n" +
	"Pagination\x12\x1c\n" +
	"\alast_id\x18\x01 \x01(\tH\x00R\x06lastId\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05countB\n" +
	"\n" +
	"\b_last_idB\xc6\x01\n" +
	"\x14com.bricks.v1.commonB\x0fPaginationProtoP\x01Z;github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/common\xa2\x02\x03BVC\xaa\x02\x10Bricks.V1.Common\xca\x02\x10Bricks\\V1\\Common\xe2\x02\x1cBricks\\V1\\Common\\GPBMetadata\xea\x02\x12Bricks::V1::Commonb\x06proto3"

var (
	file_bricks_v1_common_pagination_proto_rawDescOnce sync.Once
	file_bricks_v1_common_pagination_proto_rawDescData []byte
)

func file_bricks_v1_common_pagination_proto_rawDescGZIP() []byte {
	file_bricks_v1_common_pagination_proto_rawDescOnce.Do(func() {
		file_bricks_v1_common_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_common_pagination_proto_rawDesc), len(file_bricks_v1_common_pagination_proto_rawDesc)))
	})
	return file_bricks_v1_common_pagination_proto_rawDescData
}

var file_bricks_v1_common_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bricks_v1_common_pagination_proto_goTypes = []any{
	(*Pagination)(nil), // 0: bricks.v1.common.Pagination
}
var file_bricks_v1_common_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bricks_v1_common_pagination_proto_init() }
func file_bricks_v1_common_pagination_proto_init() {
	if File_bricks_v1_common_pagination_proto != nil {
		return
	}
	file_bricks_v1_common_pagination_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_common_pagination_proto_rawDesc), len(file_bricks_v1_common_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bricks_v1_common_pagination_proto_goTypes,
		DependencyIndexes: file_bricks_v1_common_pagination_proto_depIdxs,
		MessageInfos:      file_bricks_v1_common_pagination_proto_msgTypes,
	}.Build()
	File_bricks_v1_common_pagination_proto = out.File
	file_bricks_v1_common_pagination_proto_goTypes = nil
	file_bricks_v1_common_pagination_proto_depIdxs = nil
}
