apiVersion: v1
kind: Service
metadata:
  name: settings-valkey
  namespace: bricks
spec:
  selector:
    app: settings-valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
