// Code generated by MockGen. DO NOT EDIT.
// Source: item/catalog_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source item/catalog_grpc.pb.go -destination item/mock/catalog_grpc.pb.go -package mockitem
//

// Package mockitem is a generated GoMock package.
package mockitem

import (
	context "context"
	reflect "reflect"

	item "github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/item"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCatalogServiceClient is a mock of CatalogServiceClient interface.
type MockCatalogServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceClientMockRecorder
	isgomock struct{}
}

// MockCatalogServiceClientMockRecorder is the mock recorder for MockCatalogServiceClient.
type MockCatalogServiceClientMockRecorder struct {
	mock *MockCatalogServiceClient
}

// NewMockCatalogServiceClient creates a new mock instance.
func NewMockCatalogServiceClient(ctrl *gomock.Controller) *MockCatalogServiceClient {
	mock := &MockCatalogServiceClient{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceClient) EXPECT() *MockCatalogServiceClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCatalogServiceClient) Get(ctx context.Context, in *item.GetRequest, opts ...grpc.CallOption) (*item.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*item.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCatalogServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCatalogServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockCatalogServiceClient) List(ctx context.Context, in *item.ListRequest, opts ...grpc.CallOption) (*item.ListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*item.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCatalogServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCatalogServiceClient)(nil).List), varargs...)
}

// ListAvailable mocks base method.
func (m *MockCatalogServiceClient) ListAvailable(ctx context.Context, in *item.ListAvailableRequest, opts ...grpc.CallOption) (*item.ListAvailableResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAvailable", varargs...)
	ret0, _ := ret[0].(*item.ListAvailableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailable indicates an expected call of ListAvailable.
func (mr *MockCatalogServiceClientMockRecorder) ListAvailable(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailable", reflect.TypeOf((*MockCatalogServiceClient)(nil).ListAvailable), varargs...)
}

// UpdateItem mocks base method.
func (m *MockCatalogServiceClient) UpdateItem(ctx context.Context, in *item.UpdateItemRequest, opts ...grpc.CallOption) (*item.UpdateItemResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateItem", varargs...)
	ret0, _ := ret[0].(*item.UpdateItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockCatalogServiceClientMockRecorder) UpdateItem(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockCatalogServiceClient)(nil).UpdateItem), varargs...)
}

// MockCatalogServiceServer is a mock of CatalogServiceServer interface.
type MockCatalogServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceServerMockRecorder
	isgomock struct{}
}

// MockCatalogServiceServerMockRecorder is the mock recorder for MockCatalogServiceServer.
type MockCatalogServiceServerMockRecorder struct {
	mock *MockCatalogServiceServer
}

// NewMockCatalogServiceServer creates a new mock instance.
func NewMockCatalogServiceServer(ctrl *gomock.Controller) *MockCatalogServiceServer {
	mock := &MockCatalogServiceServer{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceServer) EXPECT() *MockCatalogServiceServerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCatalogServiceServer) Get(arg0 context.Context, arg1 *item.GetRequest) (*item.GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*item.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCatalogServiceServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCatalogServiceServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockCatalogServiceServer) List(arg0 context.Context, arg1 *item.ListRequest) (*item.ListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*item.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCatalogServiceServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCatalogServiceServer)(nil).List), arg0, arg1)
}

// ListAvailable mocks base method.
func (m *MockCatalogServiceServer) ListAvailable(arg0 context.Context, arg1 *item.ListAvailableRequest) (*item.ListAvailableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailable", arg0, arg1)
	ret0, _ := ret[0].(*item.ListAvailableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailable indicates an expected call of ListAvailable.
func (mr *MockCatalogServiceServerMockRecorder) ListAvailable(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailable", reflect.TypeOf((*MockCatalogServiceServer)(nil).ListAvailable), arg0, arg1)
}

// UpdateItem mocks base method.
func (m *MockCatalogServiceServer) UpdateItem(arg0 context.Context, arg1 *item.UpdateItemRequest) (*item.UpdateItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", arg0, arg1)
	ret0, _ := ret[0].(*item.UpdateItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockCatalogServiceServerMockRecorder) UpdateItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockCatalogServiceServer)(nil).UpdateItem), arg0, arg1)
}

// mustEmbedUnimplementedCatalogServiceServer mocks base method.
func (m *MockCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCatalogServiceServer")
}

// mustEmbedUnimplementedCatalogServiceServer indicates an expected call of mustEmbedUnimplementedCatalogServiceServer.
func (mr *MockCatalogServiceServerMockRecorder) mustEmbedUnimplementedCatalogServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCatalogServiceServer", reflect.TypeOf((*MockCatalogServiceServer)(nil).mustEmbedUnimplementedCatalogServiceServer))
}

// MockUnsafeCatalogServiceServer is a mock of UnsafeCatalogServiceServer interface.
type MockUnsafeCatalogServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCatalogServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeCatalogServiceServerMockRecorder is the mock recorder for MockUnsafeCatalogServiceServer.
type MockUnsafeCatalogServiceServerMockRecorder struct {
	mock *MockUnsafeCatalogServiceServer
}

// NewMockUnsafeCatalogServiceServer creates a new mock instance.
func NewMockUnsafeCatalogServiceServer(ctrl *gomock.Controller) *MockUnsafeCatalogServiceServer {
	mock := &MockUnsafeCatalogServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCatalogServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCatalogServiceServer) EXPECT() *MockUnsafeCatalogServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCatalogServiceServer mocks base method.
func (m *MockUnsafeCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCatalogServiceServer")
}

// mustEmbedUnimplementedCatalogServiceServer indicates an expected call of mustEmbedUnimplementedCatalogServiceServer.
func (mr *MockUnsafeCatalogServiceServerMockRecorder) mustEmbedUnimplementedCatalogServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCatalogServiceServer", reflect.TypeOf((*MockUnsafeCatalogServiceServer)(nil).mustEmbedUnimplementedCatalogServiceServer))
}
