apiVersion: v1
kind: Service
metadata:
  name: persistence-valkey
  namespace: bricks
spec:
  selector:
    app: persistence-valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
