resources:
  - ../base
patches:
  - path: patches/deployment.yaml
configMapGenerator:
  - name: auth-config
    namespace: bricks
    envs:
      - config.env
images:
  - name: ghcr.io/purplepudding/bricks/auth
    newTag: v0.24.4
