resources:
  - ../base
  - resources/namespace.yaml
  - resources/valkey/deployment.yaml
  - resources/valkey/service.yaml

configMapGenerator:
  - name: settings-config
    namespace: bricks
    envs:
      - config.env
