// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/settings/global.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetGlobalSettingsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Settings      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalSettingsRequest) Reset() {
	*x = SetGlobalSettingsRequest{}
	mi := &file_bricks_v1_settings_global_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalSettingsRequest) ProtoMessage() {}

func (x *SetGlobalSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_global_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetGlobalSettingsRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_global_proto_rawDescGZIP(), []int{0}
}

func (x *SetGlobalSettingsRequest) GetSettings() map[string]*structpb.Value {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetGlobalSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalSettingsResponse) Reset() {
	*x = SetGlobalSettingsResponse{}
	mi := &file_bricks_v1_settings_global_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalSettingsResponse) ProtoMessage() {}

func (x *SetGlobalSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_global_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetGlobalSettingsResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_global_proto_rawDescGZIP(), []int{1}
}

var File_bricks_v1_settings_global_proto protoreflect.FileDescriptor

const file_bricks_v1_settings_global_proto_rawDesc = "" +
	"\n" +
	"\x1fbricks/v1/settings/global.proto\x12\x12bricks.v1.settings\x1a\x1cgoogle/protobuf/struct.proto\"\xc7\x01\n" +
	"\x18SetGlobalSettingsRequest\x12V\n" +
	"\bsettings\x18\x01 \x03(\v2:.bricks.v1.settings.SetGlobalSettingsRequest.SettingsEntryR\bsettings\x1aS\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x1b\n" +
	"\x19SetGlobalSettingsResponse2\x8b\x01\n" +
	"\x15GlobalSettingsService\x12r\n" +
	"\x11SetGlobalSettings\x12,.bricks.v1.settings.SetGlobalSettingsRequest\x1a-.bricks.v1.settings.SetGlobalSettingsResponse\"\x00B\xce\x01\n" +
	"\x16com.bricks.v1.settingsB\vGlobalProtoP\x01Z=github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/settings\xa2\x02\x03BVS\xaa\x02\x12Bricks.V1.Settings\xca\x02\x12Bricks\\V1\\Settings\xe2\x02\x1eBricks\\V1\\Settings\\GPBMetadata\xea\x02\x14Bricks::V1::Settingsb\x06proto3"

var (
	file_bricks_v1_settings_global_proto_rawDescOnce sync.Once
	file_bricks_v1_settings_global_proto_rawDescData []byte
)

func file_bricks_v1_settings_global_proto_rawDescGZIP() []byte {
	file_bricks_v1_settings_global_proto_rawDescOnce.Do(func() {
		file_bricks_v1_settings_global_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_global_proto_rawDesc), len(file_bricks_v1_settings_global_proto_rawDesc)))
	})
	return file_bricks_v1_settings_global_proto_rawDescData
}

var file_bricks_v1_settings_global_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bricks_v1_settings_global_proto_goTypes = []any{
	(*SetGlobalSettingsRequest)(nil),  // 0: bricks.v1.settings.SetGlobalSettingsRequest
	(*SetGlobalSettingsResponse)(nil), // 1: bricks.v1.settings.SetGlobalSettingsResponse
	nil,                               // 2: bricks.v1.settings.SetGlobalSettingsRequest.SettingsEntry
	(*structpb.Value)(nil),            // 3: google.protobuf.Value
}
var file_bricks_v1_settings_global_proto_depIdxs = []int32{
	2, // 0: bricks.v1.settings.SetGlobalSettingsRequest.settings:type_name -> bricks.v1.settings.SetGlobalSettingsRequest.SettingsEntry
	3, // 1: bricks.v1.settings.SetGlobalSettingsRequest.SettingsEntry.value:type_name -> google.protobuf.Value
	0, // 2: bricks.v1.settings.GlobalSettingsService.SetGlobalSettings:input_type -> bricks.v1.settings.SetGlobalSettingsRequest
	1, // 3: bricks.v1.settings.GlobalSettingsService.SetGlobalSettings:output_type -> bricks.v1.settings.SetGlobalSettingsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bricks_v1_settings_global_proto_init() }
func file_bricks_v1_settings_global_proto_init() {
	if File_bricks_v1_settings_global_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_global_proto_rawDesc), len(file_bricks_v1_settings_global_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_settings_global_proto_goTypes,
		DependencyIndexes: file_bricks_v1_settings_global_proto_depIdxs,
		MessageInfos:      file_bricks_v1_settings_global_proto_msgTypes,
	}.Build()
	File_bricks_v1_settings_global_proto = out.File
	file_bricks_v1_settings_global_proto_goTypes = nil
	file_bricks_v1_settings_global_proto_depIdxs = nil
}
