// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/settings/items.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemParametersRequest) Reset() {
	*x = GetItemParametersRequest{}
	mi := &file_bricks_v1_settings_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemParametersRequest) ProtoMessage() {}

func (x *GetItemParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemParametersRequest.ProtoReflect.Descriptor instead.
func (*GetItemParametersRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_items_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemParametersRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetItemParametersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Parameters    map[string]*structpb.Value `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemParametersResponse) Reset() {
	*x = GetItemParametersResponse{}
	mi := &file_bricks_v1_settings_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemParametersResponse) ProtoMessage() {}

func (x *GetItemParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemParametersResponse.ProtoReflect.Descriptor instead.
func (*GetItemParametersResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_items_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemParametersResponse) GetParameters() map[string]*structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SetItemParametersRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ItemId        string                     `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Parameters    map[string]*structpb.Value `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemParametersRequest) Reset() {
	*x = SetItemParametersRequest{}
	mi := &file_bricks_v1_settings_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemParametersRequest) ProtoMessage() {}

func (x *SetItemParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemParametersRequest.ProtoReflect.Descriptor instead.
func (*SetItemParametersRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_items_proto_rawDescGZIP(), []int{2}
}

func (x *SetItemParametersRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SetItemParametersRequest) GetParameters() map[string]*structpb.Value {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SetItemParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemParametersResponse) Reset() {
	*x = SetItemParametersResponse{}
	mi := &file_bricks_v1_settings_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemParametersResponse) ProtoMessage() {}

func (x *SetItemParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemParametersResponse.ProtoReflect.Descriptor instead.
func (*SetItemParametersResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_items_proto_rawDescGZIP(), []int{3}
}

var File_bricks_v1_settings_items_proto protoreflect.FileDescriptor

const file_bricks_v1_settings_items_proto_rawDesc = "" +
	"\n" +
	"\x1ebricks/v1/settings/items.proto\x12\x12bricks.v1.settings\x1a\x1cgoogle/protobuf/struct.proto\"3\n" +
	"\x18GetItemParametersRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\xd1\x01\n" +
	"\x19GetItemParametersResponse\x12]\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2=.bricks.v1.settings.GetItemParametersResponse.ParametersEntryR\n" +
	"parameters\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x18SetItemParametersRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\\\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2<.bricks.v1.settings.SetItemParametersRequest.ParametersEntryR\n" +
	"parameters\x1aU\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x1b\n" +
	"\x19SetItemParametersResponse2\xff\x01\n" +
	"\x15ItemParametersService\x12r\n" +
	"\x11GetItemParameters\x12,.bricks.v1.settings.GetItemParametersRequest\x1a-.bricks.v1.settings.GetItemParametersResponse\"\x00\x12r\n" +
	"\x11SetItemParameters\x12,.bricks.v1.settings.SetItemParametersRequest\x1a-.bricks.v1.settings.SetItemParametersResponse\"\x00B\xcd\x01\n" +
	"\x16com.bricks.v1.settingsB\n" +
	"ItemsProtoP\x01Z=github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/settings\xa2\x02\x03BVS\xaa\x02\x12Bricks.V1.Settings\xca\x02\x12Bricks\\V1\\Settings\xe2\x02\x1eBricks\\V1\\Settings\\GPBMetadata\xea\x02\x14Bricks::V1::Settingsb\x06proto3"

var (
	file_bricks_v1_settings_items_proto_rawDescOnce sync.Once
	file_bricks_v1_settings_items_proto_rawDescData []byte
)

func file_bricks_v1_settings_items_proto_rawDescGZIP() []byte {
	file_bricks_v1_settings_items_proto_rawDescOnce.Do(func() {
		file_bricks_v1_settings_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_items_proto_rawDesc), len(file_bricks_v1_settings_items_proto_rawDesc)))
	})
	return file_bricks_v1_settings_items_proto_rawDescData
}

var file_bricks_v1_settings_items_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bricks_v1_settings_items_proto_goTypes = []any{
	(*GetItemParametersRequest)(nil),  // 0: bricks.v1.settings.GetItemParametersRequest
	(*GetItemParametersResponse)(nil), // 1: bricks.v1.settings.GetItemParametersResponse
	(*SetItemParametersRequest)(nil),  // 2: bricks.v1.settings.SetItemParametersRequest
	(*SetItemParametersResponse)(nil), // 3: bricks.v1.settings.SetItemParametersResponse
	nil,                               // 4: bricks.v1.settings.GetItemParametersResponse.ParametersEntry
	nil,                               // 5: bricks.v1.settings.SetItemParametersRequest.ParametersEntry
	(*structpb.Value)(nil),            // 6: google.protobuf.Value
}
var file_bricks_v1_settings_items_proto_depIdxs = []int32{
	4, // 0: bricks.v1.settings.GetItemParametersResponse.parameters:type_name -> bricks.v1.settings.GetItemParametersResponse.ParametersEntry
	5, // 1: bricks.v1.settings.SetItemParametersRequest.parameters:type_name -> bricks.v1.settings.SetItemParametersRequest.ParametersEntry
	6, // 2: bricks.v1.settings.GetItemParametersResponse.ParametersEntry.value:type_name -> google.protobuf.Value
	6, // 3: bricks.v1.settings.SetItemParametersRequest.ParametersEntry.value:type_name -> google.protobuf.Value
	0, // 4: bricks.v1.settings.ItemParametersService.GetItemParameters:input_type -> bricks.v1.settings.GetItemParametersRequest
	2, // 5: bricks.v1.settings.ItemParametersService.SetItemParameters:input_type -> bricks.v1.settings.SetItemParametersRequest
	1, // 6: bricks.v1.settings.ItemParametersService.GetItemParameters:output_type -> bricks.v1.settings.GetItemParametersResponse
	3, // 7: bricks.v1.settings.ItemParametersService.SetItemParameters:output_type -> bricks.v1.settings.SetItemParametersResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bricks_v1_settings_items_proto_init() }
func file_bricks_v1_settings_items_proto_init() {
	if File_bricks_v1_settings_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_items_proto_rawDesc), len(file_bricks_v1_settings_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_settings_items_proto_goTypes,
		DependencyIndexes: file_bricks_v1_settings_items_proto_depIdxs,
		MessageInfos:      file_bricks_v1_settings_items_proto_msgTypes,
	}.Build()
	File_bricks_v1_settings_items_proto = out.File
	file_bricks_v1_settings_items_proto_goTypes = nil
	file_bricks_v1_settings_items_proto_depIdxs = nil
}
