// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/settings/service.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceSettingsRequest) Reset() {
	*x = GetServiceSettingsRequest{}
	mi := &file_bricks_v1_settings_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceSettingsRequest) ProtoMessage() {}

func (x *GetServiceSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceSettingsRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceSettingsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type GetServiceSettingsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Settings      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceSettingsResponse) Reset() {
	*x = GetServiceSettingsResponse{}
	mi := &file_bricks_v1_settings_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceSettingsResponse) ProtoMessage() {}

func (x *GetServiceSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceSettingsResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceSettingsResponse) GetSettings() map[string]*structpb.Value {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetServiceSettingsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Service       string                     `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Settings      map[string]*structpb.Value `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceSettingsRequest) Reset() {
	*x = SetServiceSettingsRequest{}
	mi := &file_bricks_v1_settings_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceSettingsRequest) ProtoMessage() {}

func (x *SetServiceSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetServiceSettingsRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetServiceSettingsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SetServiceSettingsRequest) GetSettings() map[string]*structpb.Value {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetServiceSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceSettingsResponse) Reset() {
	*x = SetServiceSettingsResponse{}
	mi := &file_bricks_v1_settings_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceSettingsResponse) ProtoMessage() {}

func (x *SetServiceSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_settings_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetServiceSettingsResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_settings_service_proto_rawDescGZIP(), []int{3}
}

var File_bricks_v1_settings_service_proto protoreflect.FileDescriptor

const file_bricks_v1_settings_service_proto_rawDesc = "" +
	"\n" +
	" bricks/v1/settings/service.proto\x12\x12bricks.v1.settings\x1a\x1cgoogle/protobuf/struct.proto\"5\n" +
	"\x19GetServiceSettingsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xcb\x01\n" +
	"\x1aGetServiceSettingsResponse\x12X\n" +
	"\bsettings\x18\x01 \x03(\v2<.bricks.v1.settings.GetServiceSettingsResponse.SettingsEntryR\bsettings\x1aS\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x19SetServiceSettingsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12W\n" +
	"\bsettings\x18\x02 \x03(\v2;.bricks.v1.settings.SetServiceSettingsRequest.SettingsEntryR\bsettings\x1aS\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x1c\n" +
	"\x1aSetServiceSettingsResponse2\x86\x02\n" +
	"\x16ServiceSettingsService\x12u\n" +
	"\x12GetServiceSettings\x12-.bricks.v1.settings.GetServiceSettingsRequest\x1a..bricks.v1.settings.GetServiceSettingsResponse\"\x00\x12u\n" +
	"\x12SetServiceSettings\x12-.bricks.v1.settings.SetServiceSettingsRequest\x1a..bricks.v1.settings.SetServiceSettingsResponse\"\x00B\xcf\x01\n" +
	"\x16com.bricks.v1.settingsB\fServiceProtoP\x01Z=github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/settings\xa2\x02\x03BVS\xaa\x02\x12Bricks.V1.Settings\xca\x02\x12Bricks\\V1\\Settings\xe2\x02\x1eBricks\\V1\\Settings\\GPBMetadata\xea\x02\x14Bricks::V1::Settingsb\x06proto3"

var (
	file_bricks_v1_settings_service_proto_rawDescOnce sync.Once
	file_bricks_v1_settings_service_proto_rawDescData []byte
)

func file_bricks_v1_settings_service_proto_rawDescGZIP() []byte {
	file_bricks_v1_settings_service_proto_rawDescOnce.Do(func() {
		file_bricks_v1_settings_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_service_proto_rawDesc), len(file_bricks_v1_settings_service_proto_rawDesc)))
	})
	return file_bricks_v1_settings_service_proto_rawDescData
}

var file_bricks_v1_settings_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bricks_v1_settings_service_proto_goTypes = []any{
	(*GetServiceSettingsRequest)(nil),  // 0: bricks.v1.settings.GetServiceSettingsRequest
	(*GetServiceSettingsResponse)(nil), // 1: bricks.v1.settings.GetServiceSettingsResponse
	(*SetServiceSettingsRequest)(nil),  // 2: bricks.v1.settings.SetServiceSettingsRequest
	(*SetServiceSettingsResponse)(nil), // 3: bricks.v1.settings.SetServiceSettingsResponse
	nil,                                // 4: bricks.v1.settings.GetServiceSettingsResponse.SettingsEntry
	nil,                                // 5: bricks.v1.settings.SetServiceSettingsRequest.SettingsEntry
	(*structpb.Value)(nil),             // 6: google.protobuf.Value
}
var file_bricks_v1_settings_service_proto_depIdxs = []int32{
	4, // 0: bricks.v1.settings.GetServiceSettingsResponse.settings:type_name -> bricks.v1.settings.GetServiceSettingsResponse.SettingsEntry
	5, // 1: bricks.v1.settings.SetServiceSettingsRequest.settings:type_name -> bricks.v1.settings.SetServiceSettingsRequest.SettingsEntry
	6, // 2: bricks.v1.settings.GetServiceSettingsResponse.SettingsEntry.value:type_name -> google.protobuf.Value
	6, // 3: bricks.v1.settings.SetServiceSettingsRequest.SettingsEntry.value:type_name -> google.protobuf.Value
	0, // 4: bricks.v1.settings.ServiceSettingsService.GetServiceSettings:input_type -> bricks.v1.settings.GetServiceSettingsRequest
	2, // 5: bricks.v1.settings.ServiceSettingsService.SetServiceSettings:input_type -> bricks.v1.settings.SetServiceSettingsRequest
	1, // 6: bricks.v1.settings.ServiceSettingsService.GetServiceSettings:output_type -> bricks.v1.settings.GetServiceSettingsResponse
	3, // 7: bricks.v1.settings.ServiceSettingsService.SetServiceSettings:output_type -> bricks.v1.settings.SetServiceSettingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bricks_v1_settings_service_proto_init() }
func file_bricks_v1_settings_service_proto_init() {
	if File_bricks_v1_settings_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_settings_service_proto_rawDesc), len(file_bricks_v1_settings_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_settings_service_proto_goTypes,
		DependencyIndexes: file_bricks_v1_settings_service_proto_depIdxs,
		MessageInfos:      file_bricks_v1_settings_service_proto_msgTypes,
	}.Build()
	File_bricks_v1_settings_service_proto = out.File
	file_bricks_v1_settings_service_proto_goTypes = nil
	file_bricks_v1_settings_service_proto_depIdxs = nil
}
