apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: bricks
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      name: monolith
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: ghcr.io/purplepudding/bricks/monolith:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
        - name: valkey
          image: valkey/valkey:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
