resources:
  - deployment.yaml
  - service.yaml
  - gateway-service.yaml
  - auth-service.yaml
  - item-service.yaml
  - matchmaking-service.yaml
  - persistence-service.yaml
  - settings-service.yaml
