name: gateway
servingAddr: ":8080"
observabilityEnabled: true

auth:
  servingAddr: "auth:80"

item:
  servingAddr: "item:80"

matchmaking:
  servingAddr: "matchmaking:80"

persistence:
  servingAddr: "persistence:80"

settings:
  servingAddr: "settings:80"
