apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings
  namespace: bricks
  labels:
    app: settings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      name: settings
      labels:
        app: settings
    spec:
      containers:
        - name: settings
          image: ghcr.io/purplepudding/bricks/settings:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
