apiVersion: v1
kind: Service
metadata:
  name: settings
  namespace: foundation
spec:
  selector:
    app: settings
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
