// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bricks/v1/persistence/storage.proto

package persistence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypedKey:
	//
	//	*Key_PlayerKey
	//	*Key_TitleKey
	TypedKey      isKey_TypedKey `protobuf_oneof:"typed_key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetTypedKey() isKey_TypedKey {
	if x != nil {
		return x.TypedKey
	}
	return nil
}

func (x *Key) GetPlayerKey() *PlayerKey {
	if x != nil {
		if x, ok := x.TypedKey.(*Key_PlayerKey); ok {
			return x.PlayerKey
		}
	}
	return nil
}

func (x *Key) GetTitleKey() *TitleKey {
	if x != nil {
		if x, ok := x.TypedKey.(*Key_TitleKey); ok {
			return x.TitleKey
		}
	}
	return nil
}

type isKey_TypedKey interface {
	isKey_TypedKey()
}

type Key_PlayerKey struct {
	PlayerKey *PlayerKey `protobuf:"bytes,1,opt,name=player_key,json=playerKey,proto3,oneof"`
}

type Key_TitleKey struct {
	TitleKey *TitleKey `protobuf:"bytes,2,opt,name=title_key,json=titleKey,proto3,oneof"` //TODO any other category of value to be stored
}

func (*Key_PlayerKey) isKey_TypedKey() {}

func (*Key_TitleKey) isKey_TypedKey() {}

type PlayerKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       string                 `protobuf:"bytes,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Datatype      string                 `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerKey) Reset() {
	*x = PlayerKey{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerKey) ProtoMessage() {}

func (x *PlayerKey) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerKey.ProtoReflect.Descriptor instead.
func (*PlayerKey) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerKey) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *PlayerKey) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerKey) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

type TitleKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       string                 `protobuf:"bytes,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Datatype      string                 `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleKey) Reset() {
	*x = TitleKey{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleKey) ProtoMessage() {}

func (x *TitleKey) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleKey.ProtoReflect.Descriptor instead.
func (*TitleKey) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{2}
}

func (x *TitleKey) GetTitleId() string {
	if x != nil {
		return x.TitleId
	}
	return ""
}

func (x *TitleKey) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Struct       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{5}
}

func (x *SetRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetRequest) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{6}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *structpb.Struct       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{8}
}

func (x *WatchResponse) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*UpdateRequest_Get
	//	*UpdateRequest_Set
	RequestType   isUpdateRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequest) GetRequestType() isUpdateRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *UpdateRequest) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.RequestType.(*UpdateRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *UpdateRequest) GetSet() *SetRequest {
	if x != nil {
		if x, ok := x.RequestType.(*UpdateRequest_Set); ok {
			return x.Set
		}
	}
	return nil
}

type isUpdateRequest_RequestType interface {
	isUpdateRequest_RequestType()
}

type UpdateRequest_Get struct {
	Get *GetRequest `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type UpdateRequest_Set struct {
	Set *SetRequest `protobuf:"bytes,2,opt,name=set,proto3,oneof"`
}

func (*UpdateRequest_Get) isUpdateRequest_RequestType() {}

func (*UpdateRequest_Set) isUpdateRequest_RequestType() {}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*UpdateResponse_Get
	//	*UpdateResponse_Set
	ResponseType  isUpdateResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bricks_v1_persistence_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_bricks_v1_persistence_storage_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResponse) GetResponseType() isUpdateResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *UpdateResponse) GetGet() *GetResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*UpdateResponse_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *UpdateResponse) GetSet() *SetResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*UpdateResponse_Set); ok {
			return x.Set
		}
	}
	return nil
}

type isUpdateResponse_ResponseType interface {
	isUpdateResponse_ResponseType()
}

type UpdateResponse_Get struct {
	Get *GetResponse `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type UpdateResponse_Set struct {
	Set *SetResponse `protobuf:"bytes,2,opt,name=set,proto3,oneof"`
}

func (*UpdateResponse_Get) isUpdateResponse_ResponseType() {}

func (*UpdateResponse_Set) isUpdateResponse_ResponseType() {}

var File_bricks_v1_persistence_storage_proto protoreflect.FileDescriptor

const file_bricks_v1_persistence_storage_proto_rawDesc = "" +
	"\n" +
	"#bricks/v1/persistence/storage.proto\x12\x15bricks.v1.persistence\x1a\x1cgoogle/protobuf/struct.proto\"\x95\x01\n" +
	"\x03Key\x12A\n" +
	"\n" +
	"player_key\x18\x01 \x01(\v2 .bricks.v1.persistence.PlayerKeyH\x00R\tplayerKey\x12>\n" +
	"\ttitle_key\x18\x02 \x01(\v2\x1f.bricks.v1.persistence.TitleKeyH\x00R\btitleKeyB\v\n" +
	"\ttyped_key\"_\n" +
	"\tPlayerKey\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\tR\atitleId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bdatatype\x18\x03 \x01(\tR\bdatatype\"A\n" +
	"\bTitleKey\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\tR\atitleId\x12\x1a\n" +
	"\bdatatype\x18\x02 \x01(\tR\bdatatype\":\n" +
	"\n" +
	"GetRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.bricks.v1.persistence.KeyR\x03key\"<\n" +
	"\vGetResponse\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05value\"i\n" +
	"\n" +
	"SetRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.bricks.v1.persistence.KeyR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"\r\n" +
	"\vSetResponse\"<\n" +
	"\fWatchRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.bricks.v1.persistence.KeyR\x03key\">\n" +
	"\rWatchResponse\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05value\"\x8d\x01\n" +
	"\rUpdateRequest\x125\n" +
	"\x03get\x18\x01 \x01(\v2!.bricks.v1.persistence.GetRequestH\x00R\x03get\x125\n" +
	"\x03set\x18\x02 \x01(\v2!.bricks.v1.persistence.SetRequestH\x00R\x03setB\x0e\n" +
	"\frequest_type\"\x91\x01\n" +
	"\x0eUpdateResponse\x126\n" +
	"\x03get\x18\x01 \x01(\v2\".bricks.v1.persistence.GetResponseH\x00R\x03get\x126\n" +
	"\x03set\x18\x02 \x01(\v2\".bricks.v1.persistence.SetResponseH\x00R\x03setB\x0f\n" +
	"\rresponse_type2\xe5\x02\n" +
	"\x0eStorageService\x12N\n" +
	"\x03Get\x12!.bricks.v1.persistence.GetRequest\x1a\".bricks.v1.persistence.GetResponse\"\x00\x12N\n" +
	"\x03Set\x12!.bricks.v1.persistence.SetRequest\x1a\".bricks.v1.persistence.SetResponse\"\x00\x12V\n" +
	"\x05Watch\x12#.bricks.v1.persistence.WatchRequest\x1a$.bricks.v1.persistence.WatchResponse\"\x000\x01\x12[\n" +
	"\x06Update\x12$.bricks.v1.persistence.UpdateRequest\x1a%.bricks.v1.persistence.UpdateResponse\"\x00(\x010\x01B\xe1\x01\n" +
	"\x19com.bricks.v1.persistenceB\fStorageProtoP\x01Z@github.com/purplepudding/bricks/api/pkg/pb/bricks/v1/persistence\xa2\x02\x03BVP\xaa\x02\x15Bricks.V1.Persistence\xca\x02\x15Bricks\\V1\\Persistence\xe2\x02!Bricks\\V1\\Persistence\\GPBMetadata\xea\x02\x17Bricks::V1::Persistenceb\x06proto3"

var (
	file_bricks_v1_persistence_storage_proto_rawDescOnce sync.Once
	file_bricks_v1_persistence_storage_proto_rawDescData []byte
)

func file_bricks_v1_persistence_storage_proto_rawDescGZIP() []byte {
	file_bricks_v1_persistence_storage_proto_rawDescOnce.Do(func() {
		file_bricks_v1_persistence_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bricks_v1_persistence_storage_proto_rawDesc), len(file_bricks_v1_persistence_storage_proto_rawDesc)))
	})
	return file_bricks_v1_persistence_storage_proto_rawDescData
}

var file_bricks_v1_persistence_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bricks_v1_persistence_storage_proto_goTypes = []any{
	(*Key)(nil),             // 0: bricks.v1.persistence.Key
	(*PlayerKey)(nil),       // 1: bricks.v1.persistence.PlayerKey
	(*TitleKey)(nil),        // 2: bricks.v1.persistence.TitleKey
	(*GetRequest)(nil),      // 3: bricks.v1.persistence.GetRequest
	(*GetResponse)(nil),     // 4: bricks.v1.persistence.GetResponse
	(*SetRequest)(nil),      // 5: bricks.v1.persistence.SetRequest
	(*SetResponse)(nil),     // 6: bricks.v1.persistence.SetResponse
	(*WatchRequest)(nil),    // 7: bricks.v1.persistence.WatchRequest
	(*WatchResponse)(nil),   // 8: bricks.v1.persistence.WatchResponse
	(*UpdateRequest)(nil),   // 9: bricks.v1.persistence.UpdateRequest
	(*UpdateResponse)(nil),  // 10: bricks.v1.persistence.UpdateResponse
	(*structpb.Struct)(nil), // 11: google.protobuf.Struct
}
var file_bricks_v1_persistence_storage_proto_depIdxs = []int32{
	1,  // 0: bricks.v1.persistence.Key.player_key:type_name -> bricks.v1.persistence.PlayerKey
	2,  // 1: bricks.v1.persistence.Key.title_key:type_name -> bricks.v1.persistence.TitleKey
	0,  // 2: bricks.v1.persistence.GetRequest.key:type_name -> bricks.v1.persistence.Key
	11, // 3: bricks.v1.persistence.GetResponse.value:type_name -> google.protobuf.Struct
	0,  // 4: bricks.v1.persistence.SetRequest.key:type_name -> bricks.v1.persistence.Key
	11, // 5: bricks.v1.persistence.SetRequest.value:type_name -> google.protobuf.Struct
	0,  // 6: bricks.v1.persistence.WatchRequest.key:type_name -> bricks.v1.persistence.Key
	11, // 7: bricks.v1.persistence.WatchResponse.value:type_name -> google.protobuf.Struct
	3,  // 8: bricks.v1.persistence.UpdateRequest.get:type_name -> bricks.v1.persistence.GetRequest
	5,  // 9: bricks.v1.persistence.UpdateRequest.set:type_name -> bricks.v1.persistence.SetRequest
	4,  // 10: bricks.v1.persistence.UpdateResponse.get:type_name -> bricks.v1.persistence.GetResponse
	6,  // 11: bricks.v1.persistence.UpdateResponse.set:type_name -> bricks.v1.persistence.SetResponse
	3,  // 12: bricks.v1.persistence.StorageService.Get:input_type -> bricks.v1.persistence.GetRequest
	5,  // 13: bricks.v1.persistence.StorageService.Set:input_type -> bricks.v1.persistence.SetRequest
	7,  // 14: bricks.v1.persistence.StorageService.Watch:input_type -> bricks.v1.persistence.WatchRequest
	9,  // 15: bricks.v1.persistence.StorageService.Update:input_type -> bricks.v1.persistence.UpdateRequest
	4,  // 16: bricks.v1.persistence.StorageService.Get:output_type -> bricks.v1.persistence.GetResponse
	6,  // 17: bricks.v1.persistence.StorageService.Set:output_type -> bricks.v1.persistence.SetResponse
	8,  // 18: bricks.v1.persistence.StorageService.Watch:output_type -> bricks.v1.persistence.WatchResponse
	10, // 19: bricks.v1.persistence.StorageService.Update:output_type -> bricks.v1.persistence.UpdateResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_bricks_v1_persistence_storage_proto_init() }
func file_bricks_v1_persistence_storage_proto_init() {
	if File_bricks_v1_persistence_storage_proto != nil {
		return
	}
	file_bricks_v1_persistence_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*Key_PlayerKey)(nil),
		(*Key_TitleKey)(nil),
	}
	file_bricks_v1_persistence_storage_proto_msgTypes[9].OneofWrappers = []any{
		(*UpdateRequest_Get)(nil),
		(*UpdateRequest_Set)(nil),
	}
	file_bricks_v1_persistence_storage_proto_msgTypes[10].OneofWrappers = []any{
		(*UpdateResponse_Get)(nil),
		(*UpdateResponse_Set)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bricks_v1_persistence_storage_proto_rawDesc), len(file_bricks_v1_persistence_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bricks_v1_persistence_storage_proto_goTypes,
		DependencyIndexes: file_bricks_v1_persistence_storage_proto_depIdxs,
		MessageInfos:      file_bricks_v1_persistence_storage_proto_msgTypes,
	}.Build()
	File_bricks_v1_persistence_storage_proto = out.File
	file_bricks_v1_persistence_storage_proto_goTypes = nil
	file_bricks_v1_persistence_storage_proto_depIdxs = nil
}
