resources:
  - ../base
  - resources/valkey/deployment.yaml
  - resources/valkey/service.yaml
patches:
  - path: patches/deployment.yaml
configMapGenerator:
  - name: persistence-config
    namespace: bricks
    envs:
      - config.env
images:
  - name: ghcr.io/purplepudding/bricks/persistence
    newTag: v0.24.2
