apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: item

build:
  artifacts:
    - image: ghcr.io/purplepudding/foundation/item
      ko:
        main: ./cmd/item
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - internal
            - service
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: item
    port: 80
    localPort: 8080