apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: item

build:
  artifacts:
    - image: ghcr.io/purplepudding/bricks/item
      ko:
        main: ./cmd/item
        dependencies:
          paths:
            - cmd
            - config
            - deploy
            - internal
            - service
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local
  helm:
    releases:
      - name: nats
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts
        setValues:
          config:
            jetstream:
              enabled: true
              fileStore:
                pvc:
                  size: 1Gi
          natsBox:
            enabled: false

portForward:
  - resourceType: service
    resourceName: item
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: nats
    namespace: default
    port: 4222
    localPort: 4222