apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: player-persistence

build:
  artifacts:
    - image: ghcr.io/purplepudding/foundation/player-persistence
      ko:
        main: ./cmd/player-persistence
        dependencies:
          paths:
            - cmd
            - deploy
            - internal
            - ../lib
            - ../go.mod
            - ../go.sum

manifests:
  kustomize:
    paths:
      - deploy/k8s/local

portForward:
  - resourceType: service
    resourceName: player-persistence
    port: 80
    localPort: 8080