// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: foundation/v1/settings/global.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetGlobalSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*Settings            `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalSettingsRequest) Reset() {
	*x = SetGlobalSettingsRequest{}
	mi := &file_foundation_v1_settings_global_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalSettingsRequest) ProtoMessage() {}

func (x *SetGlobalSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_v1_settings_global_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetGlobalSettingsRequest) Descriptor() ([]byte, []int) {
	return file_foundation_v1_settings_global_proto_rawDescGZIP(), []int{0}
}

func (x *SetGlobalSettingsRequest) GetSettings() []*Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetGlobalSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalSettingsResponse) Reset() {
	*x = SetGlobalSettingsResponse{}
	mi := &file_foundation_v1_settings_global_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalSettingsResponse) ProtoMessage() {}

func (x *SetGlobalSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_v1_settings_global_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetGlobalSettingsResponse) Descriptor() ([]byte, []int) {
	return file_foundation_v1_settings_global_proto_rawDescGZIP(), []int{1}
}

var File_foundation_v1_settings_global_proto protoreflect.FileDescriptor

var file_foundation_v1_settings_global_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x23, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x58, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x1b, 0x0a, 0x19,
	0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93, 0x01, 0x0a, 0x15, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x7a, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x30, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x18, 0x5a, 0x16, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_foundation_v1_settings_global_proto_rawDescOnce sync.Once
	file_foundation_v1_settings_global_proto_rawDescData []byte
)

func file_foundation_v1_settings_global_proto_rawDescGZIP() []byte {
	file_foundation_v1_settings_global_proto_rawDescOnce.Do(func() {
		file_foundation_v1_settings_global_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_v1_settings_global_proto_rawDesc), len(file_foundation_v1_settings_global_proto_rawDesc)))
	})
	return file_foundation_v1_settings_global_proto_rawDescData
}

var file_foundation_v1_settings_global_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foundation_v1_settings_global_proto_goTypes = []any{
	(*SetGlobalSettingsRequest)(nil),  // 0: foundation.v1.settings.SetGlobalSettingsRequest
	(*SetGlobalSettingsResponse)(nil), // 1: foundation.v1.settings.SetGlobalSettingsResponse
	(*Settings)(nil),                  // 2: foundation.v1.settings.Settings
}
var file_foundation_v1_settings_global_proto_depIdxs = []int32{
	2, // 0: foundation.v1.settings.SetGlobalSettingsRequest.settings:type_name -> foundation.v1.settings.Settings
	0, // 1: foundation.v1.settings.GlobalSettingsService.SetGlobalSettings:input_type -> foundation.v1.settings.SetGlobalSettingsRequest
	1, // 2: foundation.v1.settings.GlobalSettingsService.SetGlobalSettings:output_type -> foundation.v1.settings.SetGlobalSettingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_foundation_v1_settings_global_proto_init() }
func file_foundation_v1_settings_global_proto_init() {
	if File_foundation_v1_settings_global_proto != nil {
		return
	}
	file_foundation_v1_settings_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_v1_settings_global_proto_rawDesc), len(file_foundation_v1_settings_global_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foundation_v1_settings_global_proto_goTypes,
		DependencyIndexes: file_foundation_v1_settings_global_proto_depIdxs,
		MessageInfos:      file_foundation_v1_settings_global_proto_msgTypes,
	}.Build()
	File_foundation_v1_settings_global_proto = out.File
	file_foundation_v1_settings_global_proto_goTypes = nil
	file_foundation_v1_settings_global_proto_depIdxs = nil
}
