apiVersion: v1
kind: Service
metadata:
  name: {{.ProjectKebab}}
  namespace: foundation
spec:
  selector:
    app: {{.ProjectKebab}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
