name: Build

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.semver.outputs.next}}

    steps:
      - uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          patchAll: 'true'
          noVersionBumpBehavior: 'patch'
          fallbackTag: 'v0.1.0'

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}

  publish-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: api/proto/

  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    needs: version

    strategy:
      matrix:
        svc:
          - auth
          - item
          - monolith
          - persistence
          - settings

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go  
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Setup ko
        uses: ko-build/setup-ko@v0.6

      - name: Build container
        run:
          GOFLAGS="-ldflags=-X=github.com/purplepudding/bricks.Version=${{needs.version.outputs.version}}" ko build ./${{matrix.svc}}/cmd/${{matrix.svc}} --tags ${{needs.version.outputs.version}} --tags latest --base-import-paths --platform=linux/amd64,linux/arm64

      - name: Update kustomization
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '${{matrix.svc}}/deploy/k8s/dev/kustomization.yaml'
          propertyPath: 'images[0].newTag'
          value: "${{steps.semver.outputs.next}}"
          commitChange: true
          message: "deploy: ${{matrix.svc}} ${{steps.semver.outputs.next}} [no ci]"
          branch: main
